version: "3"

volumes:
  mysql-data:
    driver: local


networks:
  internal:
    driver: bridge

services:
  # db:
  #   container_name: db
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: yw_dev
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: Abcd12345
  #   ports:
  #     - "3307:3306"
  #   command: --default-authentication-plugin=mysql_native_password --explicit-defaults-for-timestamp=ON
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   networks:
  #     - internal

  # server:
  #   volumes:
  #     - ./:/app # mount từ môi trường gốc vào trong để nếu các bạn thay đổi code thì bên trong sẽ tự động cập nhật
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   restart: always
  #   container_name: server
  #   ports:
  #     - 3001:3001
  #   networks:
  #     - internal
  #   depends_on:
  #     - db

  db_nestjs:
    container_name: db_nestjs
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social_network
      MYSQL_USER: admin
      MYSQL_PASSWORD: Abcd12345
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password --explicit-defaults-for-timestamp=ON
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - internal

  server_nestjs:
    volumes:
      - ./:/app # mount từ môi trường gốc vào trong để nếu các bạn thay đổi code thì bên trong sẽ tự động cập nhật
    build:
      context: ./server_nestjs
      dockerfile: Dockerfile
    restart: always
    container_name: server_nestjs
    ports:
      - 3000:3000
    networks:
      - internal
    depends_on:
      - db_nestjs

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - "/app/node_modules"
      - ".:/app"
    restart: always
    container_name: client
    networks:
      - internal
    depends_on:
      - db_nestjs